//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiceAndDragons {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.2.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int customDiceMin {
            get {
                return ((int)(this["customDiceMin"]));
            }
            set {
                this["customDiceMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int customDiceMax {
            get {
                return ((int)(this["customDiceMax"]));
            }
            set {
                this["customDiceMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool rollModeD6 {
            get {
                return ((bool)(this["rollModeD6"]));
            }
            set {
                this["rollModeD6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/Image/UI/Portreit_default.png")]
        public string imgPortreit {
            get {
                return ((string)(this["imgPortreit"]));
            }
            set {
                this["imgPortreit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Johnny Bravo")]
        public string bioName {
            get {
                return ((string)(this["bioName"]));
            }
            set {
                this["bioName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Chaotic Neutral")]
        public string bioAlignment {
            get {
                return ((string)(this["bioAlignment"]));
            }
            set {
                this["bioAlignment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Human")]
        public string bioRace {
            get {
                return ((string)(this["bioRace"]));
            }
            set {
                this["bioRace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Bard")]
        public string bioClass {
            get {
                return ((string)(this["bioClass"]));
            }
            set {
                this["bioClass"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"	The main protagonist of his own life. His shallow, boorish, and dim-witted traits lead to an incorrigible inability to attract women, as well as getting beaten up by them or just about anyone.

	During high school, Johnny was very scrawny, weighing at 98 pounds with a mullet. He had a crush on Sandy Baker, the prettiest and nicest girl in school. One day, Johnny was thrown into a trash can by a bully named Trent. Sandy intervened and made him apologize to Johnny for picking on guys without huge muscles. Realizing they were in the same Spanish class, Sandy offered to come over and study with Johnny. That night, Johnny asked Sandy to the prom; she cried and happily said yes. Knowing that he was going to go to prom with Sandy, Johnny decided that she deserved to go with a ""hunkin' stud"".")]
        public string bioFull {
            get {
                return ((string)(this["bioFull"]));
            }
            set {
                this["bioFull"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int bioLvl {
            get {
                return ((int)(this["bioLvl"]));
            }
            set {
                this["bioLvl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int bioExp {
            get {
                return ((int)(this["bioExp"]));
            }
            set {
                this["bioExp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int charSTR {
            get {
                return ((int)(this["charSTR"]));
            }
            set {
                this["charSTR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int charDEX {
            get {
                return ((int)(this["charDEX"]));
            }
            set {
                this["charDEX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int charCON {
            get {
                return ((int)(this["charCON"]));
            }
            set {
                this["charCON"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int charINT {
            get {
                return ((int)(this["charINT"]));
            }
            set {
                this["charINT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int charWIS {
            get {
                return ((int)(this["charWIS"]));
            }
            set {
                this["charWIS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int charCHA {
            get {
                return ((int)(this["charCHA"]));
            }
            set {
                this["charCHA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(+0)")]
        public string bonusSTR {
            get {
                return ((string)(this["bonusSTR"]));
            }
            set {
                this["bonusSTR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(+0)")]
        public string bonusDEX {
            get {
                return ((string)(this["bonusDEX"]));
            }
            set {
                this["bonusDEX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(+0)")]
        public string bonusCON {
            get {
                return ((string)(this["bonusCON"]));
            }
            set {
                this["bonusCON"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(+0)")]
        public string bonusINT {
            get {
                return ((string)(this["bonusINT"]));
            }
            set {
                this["bonusINT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(+0)")]
        public string bonusWIS {
            get {
                return ((string)(this["bonusWIS"]));
            }
            set {
                this["bonusWIS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(+0)")]
        public string bonusCHA {
            get {
                return ((string)(this["bonusCHA"]));
            }
            set {
                this["bonusCHA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("22")]
        public string bioAge {
            get {
                return ((string)(this["bioAge"]));
            }
            set {
                this["bioAge"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1,92m")]
        public string bioHeight {
            get {
                return ((string)(this["bioHeight"]));
            }
            set {
                this["bioHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Male")]
        public string bioSex {
            get {
                return ((string)(this["bioSex"]));
            }
            set {
                this["bioSex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Man")]
        public string bioGender {
            get {
                return ((string)(this["bioGender"]));
            }
            set {
                this["bioGender"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7-7-1997")]
        public string bioBirthD {
            get {
                return ((string)(this["bioBirthD"]));
            }
            set {
                this["bioBirthD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Aron City")]
        public string bioBirthP {
            get {
                return ((string)(this["bioBirthP"]));
            }
            set {
                this["bioBirthP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string bioBlood {
            get {
                return ((string)(this["bioBlood"]));
            }
            set {
                this["bioBlood"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\tJohnny wears a black shirt, blue jeans, black shoes, gelled up blonde hair, and " +
            "his signature sunglasses. He has a very muscular build.")]
        public string bioAppearance {
            get {
                return ((string)(this["bioAppearance"]));
            }
            set {
                this["bioAppearance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Wierd Guy, J.B.")]
        public string bioAltName {
            get {
                return ((string)(this["bioAltName"]));
            }
            set {
                this["bioAltName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Bunny Bravo, Myra Bravo, Fiona Bravo, Lou Bravo")]
        public string bioAlly {
            get {
                return ((string)(this["bioAlly"]));
            }
            set {
                this["bioAlly"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Christopher, Donny Osmond")]
        public string bioEnemy {
            get {
                return ((string)(this["bioEnemy"]));
            }
            set {
                this["bioEnemy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Large Muscles, ")]
        public string bioStrong {
            get {
                return ((string)(this["bioStrong"]));
            }
            set {
                this["bioStrong"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Extremally uncharismatic, Hated by woman,")]
        public string bioWeak {
            get {
                return ((string)(this["bioWeak"]));
            }
            set {
                this["bioWeak"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"	Johnny Bravo is an extremely dim-witted, ill-mannered and inconsiderate beefcake. He's very full of himself, constantly checking mirrors and flexing his muscles in front of women. During a conversation with women, Johnny will always try to find a way to turn the conversation around so that they are talking about him in an effort to make the girl realize his positive traits, although this effort to do so exemplifies him as a narcissist. Johnny also naively and faultily believes that all women want him, even when they express the fact that they are uninterested. Because of this, Johnny has the courage to talk to any woman without hesitation.")]
        public string bioPersonality {
            get {
                return ((string)(this["bioPersonality"]));
            }
            set {
                this["bioPersonality"] = value;
            }
        }
    }
}
